package binggallery.chinacloudsites.cn;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bingGalleryImageDaoConfig;

    private final BingGalleryImageDao bingGalleryImageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bingGalleryImageDaoConfig = daoConfigMap.get(BingGalleryImageDao.class).clone();
        bingGalleryImageDaoConfig.initIdentityScope(type);

        bingGalleryImageDao = new BingGalleryImageDao(bingGalleryImageDaoConfig, this);

        registerDao(Image.class, bingGalleryImageDao);
    }
    
    public void clear() {
        bingGalleryImageDaoConfig.getIdentityScope().clear();
    }

    public BingGalleryImageDao getBingGalleryImageDao() {
        return bingGalleryImageDao;
    }

}
