package binggallery.chinacloudsites.cn;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BING_GALLERY_IMAGE.
 */
public class BingGalleryImage {

    private Long id;
    /** Not-null value. */
    private String uid;
    private String minpix;
    private String maxpix;
    private String copyright;
    private String desc;

    public BingGalleryImage() {
    }

    public BingGalleryImage(Long id) {
        this.id = id;
    }

    public BingGalleryImage(Long id, String uid, String minpix, String maxpix, String copyright, String desc) {
        this.id = id;
        this.uid = uid;
        this.minpix = minpix;
        this.maxpix = maxpix;
        this.copyright = copyright;
        this.desc = desc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUid() {
        return uid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getMinpix() {
        return minpix;
    }

    public void setMinpix(String minpix) {
        this.minpix = minpix;
    }

    public String getMaxpix() {
        return maxpix;
    }

    public void setMaxpix(String maxpix) {
        this.maxpix = maxpix;
    }

    public String getCopyright() {
        return copyright;
    }

    public void setCopyright(String copyright) {
        this.copyright = copyright;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

}
